package model

const (
	// Method_DidMethod method "DidMethod"
	Method_DidMethod = "DidMethod"
	// Method_IsValidDid method "IsValidDid"
	Method_IsValidDid = "IsValidDid"
	// Method_AddDidDocument method "AddDidDocument"
	Method_AddDidDocument = "AddDidDocument"
	// Method_UpdateDidDocument method "UpdateDidDocument"
	Method_UpdateDidDocument = "UpdateDidDocument"
	// Method_GetDidDocument method "GetDidDocument"
	Method_GetDidDocument = "GetDidDocument"
	// Method_GetDidByPubKey method "GetDidByPubKey"
	Method_GetDidByPubKey = "GetDidByPubKey"
	// Method_GetDidByAddress method "GetDidByAddress"
	Method_GetDidByAddress = "GetDidByAddress"
	// Method_AddBlackList method "AddBlackList"
	Method_AddBlackList = "AddBlackList"
	// Method_GetBlackList method "GetBlackList"
	Method_GetBlackList = "GetBlackList"
	// Method_DeleteBlackList method "DeleteBlackList"
	Method_DeleteBlackList = "DeleteBlackList"
	// Method_AddTrustIssuer method "AddTrustIssuer"
	Method_AddTrustIssuer = "AddTrustIssuer"
	// Method_GetTrustIssuer method "GetTrustIssuer"
	Method_GetTrustIssuer = "GetTrustIssuer"
	// Method_DeleteTrustIssuer method "DeleteTrustIssuer"
	Method_DeleteTrustIssuer = "DeleteTrustIssuer"
	// Method_RevokeVc method "RevokeVc"
	Method_RevokeVc = "RevokeVc"
	// Method_GetRevokedVcList method "GetRevokedVcList"
	Method_GetRevokedVcList = "GetRevokedVcList"
	// Method_SetVcTemplate method "SetVcTemplate"
	Method_SetVcTemplate = "SetVcTemplate"
	// Method_GetVcTemplate method "GetVcTemplate"
	Method_GetVcTemplate = "GetVcTemplate"
	// Method_GetVcTemplateList method "GetVcTemplateList"
	Method_GetVcTemplateList = "GetVcTemplateList"
	// Method_VerifyVc method "VerifyVc"
	Method_VerifyVc = "VerifyVc"
	// Method_VerifyVp method "VerifyVp"
	Method_VerifyVp = "VerifyVp"
)

const (
	// Topic_SetDidDocument contract event topic "SetDidDocument"
	Topic_SetDidDocument = "DidTopic_SetDidDocument"
	// Topic_AddBlackList contract event topic "AddBlackList"
	Topic_AddBlackList = "DidTopic_AddBlackList"
	// Topic_DeleteBlackList contract event topic "DeleteBlackList"
	Topic_DeleteBlackList = "DidTopic_DeleteBlackList"
	// Topic_AddTrustIssuer contract event topic "AddTrustIssuer"
	Topic_AddTrustIssuer = "DidTopic_AddTrustIssuer"
	// Topic_DeleteTrustIssuer contract event topic "DeleteTrustIssuer"
	Topic_DeleteTrustIssuer = "DidTopic_DeleteTrustIssuer"
	// Topic_RevokeVc contract event topic "RevokeVc"
	Topic_RevokeVc = "DidTopic_RevokeVc"
	// Topic_SetVcTemplate contract event topic "SetVcTemplate"
	Topic_SetVcTemplate = "DidTopic_SetVcTemplate"
)

const (
	// Params_DidMethod parameters of the contract method "didMethod"
	Params_DidMethod = "didMethod"
	// Params_EnableTrustIssuer parameters of the contract method "enableTrustIssuer"
	Params_EnableTrustIssuer = "enableTrustIssuer"
	// Params_DidDocument parameters of the contract method "didDocument"
	Params_DidDocument = "didDocument"
	// Params_Did parameters of the contract method "did"
	Params_Did = "did"
	// Params_DidList parameters of the contract method "dids"
	Params_DidList = "dids"
	// Params_DidSearch parameters of the contract method "didSearch"
	Params_DidSearch = "didSearch"
	// Params_SearchStart parameters of the contract method "start"
	Params_SearchStart = "start"
	// Params_SearchCount parameters of the contract method "count"
	Params_SearchCount = "count"
	// Params_DidPubkey parameters of the contract method "pubKey"
	Params_DidPubkey = "pubKey"
	// Params_DidAddress parameters of the contract method "address"
	Params_DidAddress = "address"
	// Params_VcId parameters of the contract method "vcId"
	Params_VcId = "vcId"
	// Params_VcIdSearch parameters of the contract method "vcIdSearch"
	Params_VcIdSearch = "vcIdSearch"
	// Params_VcTemplateId parameters of the contract method "vcTemplateId"
	Params_VcTemplateId = "vcTemplateId"
	// Params_VcTemplateName parameters of the contract method "vcTemplateName"
	Params_VcTemplateName = "vcTemplateName"
	// Params_VcTemplate parameters of the contract method "vcTemplate"
	Params_VcTemplate = "vcTemplate"
	// Params_VcTemplateVersion parameters of the contract method "vcTemplateVersion"
	Params_VcTemplateVersion = "vcTemplateVersion"
	// Params_VcTemplateNameSearch parameters of the contract method "vcTemplateNameSearch"
	Params_VcTemplateNameSearch = "vcTemplateNameSearch"
	// Params_VcJson parameters of the contract method "vcJson"
	Params_VcJson = "vcJson"
	// Params_VpJson parameters of the contract method "vpJson"
	Params_VpJson = "vpJson"
)
